name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Eslint check
        run: npx eslint . --ext .js,.jsx

      - name: Run Tests
        run: TOKEN_SECRET=UKRANIA TOKEN_EXPIRES=20h TEST_DATABASE_URI='mongodb://localhost:27017/ecommerce-test' npm test

        env:
          CI: true
